apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: kafka-cluster-zoupi
spec:
  kafka:
    version: 2.8.0
    replicas: 2
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        tls: true
        port: 9093
        type: internal
    storage:
      type: jbod
      volumes:
      - id: 0
        type: persistent-claim
        size: 100Gi
        deleteClaim: false
  zookeeper:
    replicas: 2
    storage:
      type: persistent-claim
      size: 100Gi
      deleteClaim: false
