server:
  port: 4114
eureka:
  client:
    service-url:
      defaultZone: http://192.168.49.2:31508/eureka
spring:
  application:
    name: tag-zoupi
  data:
    mongodb:
      uri: mongodb+srv://ducanhtop1global:ducanhtop1global@zoupi.ml4hk63.mongodb.net/zoupi